---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
stages:
  Build:
    source: helloworldclone
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "f7302c3ftrial"
    cfSpace: "dev"
    cfCredentialsId: "deployonbtpcredentials"
    deployType: "standard"
    tmsUpload: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

